"""Validate the generated Mistral Vibe plugin payload (vibe/core/).

The payload is generated by scripts/build-vibe.js; these tests prove the
generated TOML and JSON artifacts are structurally valid so a Vibe session
can load the plugin without diagnostics.
"""

import json
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PAYLOAD_ROOT = REPO_ROOT / "vibe" / "core"


def _agent_toml_files():
    agents_dir = PAYLOAD_ROOT / "ai.mistral.vibe" / "agents"
    return sorted(agents_dir.glob("*.toml"))


class TestPluginManifest:
    def test_manifest_fields(self):
        manifest = json.loads((PAYLOAD_ROOT / "plugin.json").read_text(encoding="utf-8"))
        assert manifest["$schema"] == "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json"
        assert manifest["name"] == "ecc"
        assert manifest["version"] == (REPO_ROOT / "VERSION").read_text().strip()
        extension = manifest["extensions"]["ai.mistral.vibe"]
        assert extension["schemaVersion"] == 1
        assert extension["toolNamespace"] == "ecc"

    def test_manifest_field_whitelist(self):
        manifest = json.loads((PAYLOAD_ROOT / "plugin.json").read_text(encoding="utf-8"))
        allowed = {
            "$schema", "name", "version", "description", "author", "homepage",
            "repository", "license", "keywords", "extensions",
        }
        assert set(manifest) <= allowed


class TestSubagentToml:
    def test_all_agent_toml_files_parse(self):
        files = _agent_toml_files()
        assert len(files) == len(list((REPO_ROOT / "agents").glob("*.md")))
        for toml_path in files:
            agent = tomllib.loads(toml_path.read_text(encoding="utf-8"))
            assert agent["schema_version"] == 1
            assert agent["agent_type"] == "subagent"
            assert agent["display_name"]
            assert agent["description"]
            assert agent["safety"] in {"safe", "neutral", "destructive", "yolo"}
            assert isinstance(agent["instructions"], str)
            assert agent["instructions"].strip()
            for tool in agent.get("enabled_tools", []):
                assert isinstance(tool, str) and tool

    def test_file_names_are_kebab_case(self):
        for toml_path in _agent_toml_files():
            stem = toml_path.stem
            assert stem == stem.lower()
            assert all(char.isalnum() or char == "-" for char in stem)
            assert not stem.startswith("-") and not stem.endswith("-")


class TestHooksToml:
    def test_hooks_parse_with_expected_shape(self):
        hooks_path = PAYLOAD_ROOT / "ai.mistral.vibe" / "hooks.toml"
        data = tomllib.loads(hooks_path.read_text(encoding="utf-8"))
        hooks = data["hooks"]
        assert len(hooks) >= 1
        for hook in hooks:
            assert hook["type"] in {"pre_tool", "post_tool", "post_agent"}
            assert hook["command"].startswith("node scripts/hooks/vibe-hook-bridge.js ")
            runner = hook["command"].split(" ", 2)[2]
            assert (PAYLOAD_ROOT / runner).is_file(), f"runner missing: {runner}"
            assert hook["timeout"] > 0


class TestKnowledgeFrontmatter:
    def test_knowledge_entries_have_valid_frontmatter(self):
        knowledge_dir = PAYLOAD_ROOT / "ai.mistral.vibe" / "knowledge"
        entries = sorted(knowledge_dir.iterdir())
        assert len(entries) > 0
        for entry in entries:
            assert entry.is_dir()
            assert entry.name == entry.name.lower()
            know_md = entry / "KNOWLEDGE.md"
            assert know_md.is_file()
            content = know_md.read_text(encoding="utf-8")
            assert content.startswith("---\n")
            frontmatter = content.split("\n---\n", 1)[0][4:]
            fields = dict(
                line.split(":", 1)
                for line in frontmatter.splitlines()
                if ":" in line
            )
            assert fields["name"].strip() == entry.name
            description = fields["description"].strip().strip('"')
            assert 5 <= len(description) <= 300
            assert "display_name" in fields


class TestGeneratedSkills:
    def test_command_skills_have_user_invocable_frontmatter(self):
        skills_dir = PAYLOAD_ROOT / "skills"
        skill_md_files = sorted(skills_dir.glob("*/SKILL.md"))
        assert len(skill_md_files) > 0
        for skill_md in skill_md_files:
            content = skill_md.read_text(encoding="utf-8")
            assert content.startswith("---\n")
            frontmatter = content.split("\n---\n", 1)[0][4:]
            fields = dict(
                line.split(":", 1)
                for line in frontmatter.splitlines()
                if ":" in line and not line.startswith(" ")
            )
            assert fields["name"].strip() == skill_md.parent.name
            assert fields["user-invocable"].strip() == "true"
            assert "$ARGUMENTS" not in content
