/* ============================================================================
   ChemQuest — Question Bank
   ----------------------------------------------------------------------------
   Content sourced from the IB Chemistry guide (2023 syllabus, first exams 2025),
   themes Structure 1–3 and Reactivity 1–2 (typical Year-1 / first-year scope).

   HOW TO EDIT YOUR EXAM SCOPE
   ---------------------------------------------------------------------------
   • Each "zone" below is one syllabus sub-topic (e.g. Structure 1.2).
   • To REMOVE a topic from your exam (anything X'd-out or pink-highlighted on
     your sheet), set   on: false   on that zone. It vanishes from the game.
   • Zones flagged   hl: true   are "Additional higher level" extensions. If you
     are SL, you can switch them off in one click from the in-game Lab menu, or
     set on:false here.
   • To add/fix a question, copy a { ... } block. Keys:
        q   question/prompt
        a   the correct answer (also the flashcard "back")
        x   [3 wrong options] used to build multiple choice
        e   explanation shown after every answer (this is where you LEARN)
        acc [optional] extra accepted typed answers for recall mode
        d   difficulty 1=easy 2=medium 3=hard (affects XP & enemy strength)
   ============================================================================ */

window.CHEM_DATA = {
  meta: {
    title: "ChemQuest",
    subtitle: "Trials of the Periodic Realm",
    version: "1.0",
    source: "IB Chemistry guide (2023), Structure 1–3 & Reactivity 1–2"
  },

  zones: [
    /* ===================== STRUCTURE 1 ===================== */
    {
      id: "s1_1", code: "1.1", theme: "Structure 1", region: "The Shifting Sands",
      title: "Particulate Nature of Matter", sym: "H", hue: 188, hl: false, on: true,
      blurb: "Elements, compounds & mixtures, states of matter, kinetic theory.",
      q: [
        { d:1, q:"Which can NOT be chemically broken down into simpler substances?",
          a:"An element", x:["A compound","A mixture","A solution"],
          e:"An element is a primary constituent of matter made of one type of atom; it cannot be chemically broken down. Compounds can be split into elements; mixtures can be separated physically.",
          acc:["element"] },
        { d:1, q:"A compound is best described as…",
          a:"Atoms of different elements chemically bonded in a fixed ratio",
          x:["Two or more substances mixed in any ratio","A single type of atom","Particles with no chemical bonds"],
          e:"Compounds have a FIXED ratio and are chemically bonded (e.g. H₂O is always 2 H : 1 O). Mixtures have no fixed ratio and are not bonded." },
        { d:2, q:"Which statement about mixtures is correct?",
          a:"They contain substances in no fixed ratio and can be separated physically",
          x:["Their components are chemically bonded","They always form in a 1:1 ratio","They cannot be separated by physical means"],
          e:"Mixtures are not chemically bonded, have no fixed ratio, and can be separated by physical methods such as filtration, distillation or chromatography." },
        { d:1, q:"In which state do particles have a fixed shape and fixed volume?",
          a:"Solid", x:["Liquid","Gas","Plasma"],
          e:"In a solid, particles are held in fixed positions and only vibrate, giving a fixed shape and volume. Liquids take the shape of the container; gases fill it.",
          acc:["solid","solids"] },
        { d:2, q:"The change of state directly from a solid to a gas is called…",
          a:"Sublimation", x:["Deposition","Evaporation","Condensation"],
          e:"Sublimation = solid → gas (e.g. dry ice). The reverse, gas → solid, is deposition. Melting=solid→liquid, freezing=liquid→solid.",
          acc:["sublimation"] },
        { d:2, q:"Temperature in kelvin (K) is a measure of the…",
          a:"Average kinetic energy of the particles",
          x:["Total energy of the system","Total heat content","Number of particles"],
          e:"Temperature (in K) is proportional to the AVERAGE kinetic energy of particles. Heat is the total energy transferred; the two are different." },
        { d:2, q:"Convert 25 °C to kelvin.",
          a:"298 K", x:["248 K","25 K","273 K"],
          e:"K = °C + 273. So 25 + 273 = 298 K. The kelvin scale starts at absolute zero (0 K = −273 °C).",
          acc:["298","298 k"] },
        { d:3, q:"Which separation technique relies on different boiling points?",
          a:"Distillation", x:["Filtration","Recrystallization","Paper chromatography"],
          e:"Distillation separates liquids by boiling-point differences. Filtration separates insoluble solids; chromatography separates by relative attraction to phases." },
        { d:2, q:"A homogeneous mixture is one in which…",
          a:"The composition is uniform throughout",
          x:["You can see separate components","Components settle into layers","There is always a fixed ratio"],
          e:"Homogeneous mixtures (e.g. salt water) look uniform throughout. Heterogeneous mixtures (e.g. sand in water) have visibly distinct regions." }
      ]
    },
    {
      id: "s1_2", code: "1.2", theme: "Structure 1", region: "The Nuclear Forge",
      title: "The Nuclear Atom", sym: "U", hue: 38, hl: false, on: true,
      blurb: "Subatomic particles, atomic & mass number, isotopes, ions.",
      q: [
        { d:1, q:"Which particle has a relative charge of 0 and is found in the nucleus?",
          a:"Neutron", x:["Proton","Electron","Positron"],
          e:"Neutrons are neutral (charge 0) with relative mass 1, in the nucleus. Protons are +1 (nucleus); electrons are −1 (outside).",
          acc:["neutron"] },
        { d:1, q:"The atomic number (Z) of an atom equals the number of…",
          a:"Protons", x:["Neutrons","Electrons + neutrons","Nucleons"],
          e:"Z = number of protons, which defines the element. In a neutral atom, protons = electrons.",
          acc:["protons"] },
        { d:2, q:"Mass number (A) is equal to…",
          a:"Protons + neutrons", x:["Protons only","Protons + electrons","Neutrons − protons"],
          e:"A = protons + neutrons (the nucleons). Number of neutrons = A − Z." },
        { d:2, q:"An atom ³⁵₁₇Cl has how many neutrons?",
          a:"18", x:["17","35","52"],
          e:"Neutrons = A − Z = 35 − 17 = 18. Protons = 17, and a neutral atom has 17 electrons.",
          acc:["18"] },
        { d:1, q:"Isotopes of an element have the same number of protons but different numbers of…",
          a:"Neutrons", x:["Electrons","Protons","Energy levels"],
          e:"Isotopes = same element (same Z, same protons) but different numbers of neutrons, so different mass numbers.",
          acc:["neutrons"] },
        { d:2, q:"How many electrons are in the ion Mg²⁺ (Z = 12)?",
          a:"10", x:["12","14","2"],
          e:"A 2+ ion has lost 2 electrons: 12 − 2 = 10 electrons (it has the configuration of neon).",
          acc:["10"] },
        { d:3, q:"Chlorine has isotopes ³⁵Cl (75%) and ³⁷Cl (25%). Its relative atomic mass is…",
          a:"35.5", x:["36.0","35.0","37.0"],
          e:"Ar = weighted mean = (35×0.75) + (37×0.25) = 26.25 + 9.25 = 35.5.",
          acc:["35.5"] },
        { d:2, q:"Why is the mass of the electron usually considered negligible?",
          a:"It is about 1/1836 the mass of a proton",
          x:["It has no charge","It is outside the nucleus","It moves very fast"],
          e:"An electron's mass is ~1/1836 that of a proton or neutron, so it contributes almost nothing to the atom's mass." },
        { d:2, q:"Relative atomic mass (Ar) is measured relative to…",
          a:"1/12 the mass of a carbon-12 atom",
          x:["The mass of a hydrogen atom","The mass of a proton","One mole of carbon"],
          e:"Masses of atoms are compared on a scale where carbon-12 is exactly 12. Ar has no units." }
      ]
    },
    {
      id: "s1_3", code: "1.3", theme: "Structure 1", region: "The Spectral Heights",
      title: "Electron Configurations", sym: "Ne", hue: 280, hl: false, on: true,
      blurb: "Emission spectra, energy levels, orbitals, Aufbau, Hund, Pauli.",
      q: [
        { d:2, q:"Emission spectra are produced when electrons…",
          a:"Fall from a higher to a lower energy level, emitting photons",
          x:["Are removed from the atom","Jump to higher energy levels","Collide with the nucleus"],
          e:"When an excited electron drops to a lower level, it emits a photon of fixed energy (E = hf), producing a coloured line in the spectrum." },
        { d:2, q:"A line emission spectrum provides evidence that electron energy levels are…",
          a:"Discrete (quantized)", x:["Continuous","Random","Equally spaced at all energies"],
          e:"Distinct lines (not a continuous band) show electrons occupy only fixed, discrete energy levels. Lines converge at higher energy." },
        { d:2, q:"The maximum number of electrons in main energy level n is given by…",
          a:"2n²", x:["2n","n²","8n"],
          e:"Level n holds up to 2n² electrons: n=1→2, n=2→8, n=3→18, n=4→32.",
          acc:["2n2","2n^2"] },
        { d:1, q:"How many electrons can a single orbital hold?",
          a:"2 (with opposite spin)", x:["1","6","8"],
          e:"Each orbital holds a maximum of 2 electrons with opposite spins (Pauli exclusion principle).",
          acc:["2","two"] },
        { d:2, q:"How many orbitals are in a p sublevel?",
          a:"3", x:["1","5","7"],
          e:"s has 1 orbital (2 e⁻), p has 3 (6 e⁻), d has 5 (10 e⁻), f has 7 (14 e⁻).",
          acc:["3","three"] },
        { d:2, q:"The Aufbau principle states that electrons fill…",
          a:"The lowest available energy levels first",
          x:["Orbitals singly before pairing","The highest levels first","Only s orbitals"],
          e:"Aufbau = build up from lowest energy. Hund's rule = fill orbitals singly first; Pauli = opposite spins / max 2 per orbital." },
        { d:3, q:"Which fills first according to the Aufbau order?",
          a:"4s before 3d", x:["3d before 4s","4p before 4s","3d before 3p"],
          e:"4s is slightly lower in energy than 3d, so it fills first (e.g. Ca = [Ar]4s²; then 3d fills for transition metals)." },
        { d:3, q:"What is the full electron configuration of chromium (Z = 24)?",
          a:"1s²2s²2p⁶3s²3p⁶3d⁵4s¹",
          x:["1s²2s²2p⁶3s²3p⁶3d⁴4s²","1s²2s²2p⁶3s²3p⁶4s²4p⁴","1s²2s²2p⁶3s²3p⁶3d⁶"],
          e:"Cr is an exception: a half-filled 3d⁵ with 4s¹ is more stable than 3d⁴4s². Copper is similar (3d¹⁰4s¹).",
          acc:["[ar]3d5 4s1","3d5 4s1"] },
        { d:2, q:"The condensed configuration of sulfur (Z = 16) is…",
          a:"[Ne]3s²3p⁴", x:["[Ar]3s²3p⁴","[Ne]3s²3p⁶","[He]2s²2p⁴"],
          e:"Use the previous noble gas (Ne, Z=10) as a core, then add 3s²3p⁴ for the remaining 6 electrons.",
          acc:["[ne]3s2 3p4"] }
      ]
    },
    {
      id: "s1_4", code: "1.4", theme: "Structure 1", region: "The Counting House",
      title: "Counting Particles: The Mole", sym: "C", hue: 140, hl: false, on: true,
      blurb: "The mole, Avogadro constant, molar mass, formulas, concentration.",
      q: [
        { d:1, q:"The Avogadro constant is approximately…",
          a:"6.02 × 10²³ mol⁻¹", x:["6.02 × 10²⁴ mol⁻¹","3.01 × 10²³ mol⁻¹","1.66 × 10⁻²⁴ mol⁻¹"],
          e:"One mole contains 6.02 × 10²³ elementary entities (atoms, molecules, ions…). It is the SI unit of amount of substance.",
          acc:["6.02e23","6.02 x 10^23"] },
        { d:2, q:"How many molecules are in 2.0 mol of water?",
          a:"1.2 × 10²⁴", x:["6.02 × 10²³","3.0 × 10²³","1.2 × 10²³"],
          e:"Number = n × Nₐ = 2.0 × 6.02 × 10²³ = 1.204 × 10²⁴ molecules.",
          acc:["1.2e24","1.20e24"] },
        { d:1, q:"The units of molar mass (M) are…",
          a:"g mol⁻¹", x:["mol g⁻¹","g","mol dm⁻³"],
          e:"Molar mass M has units g mol⁻¹. Use n = m / M to relate mass, moles and molar mass.",
          acc:["g/mol","g mol-1"] },
        { d:2, q:"What is the amount (in mol) of 18 g of water (M = 18 g mol⁻¹)?",
          a:"1.0 mol", x:["18 mol","0.5 mol","2.0 mol"],
          e:"n = m / M = 18 / 18 = 1.0 mol.",
          acc:["1","1.0","1 mol"] },
        { d:2, q:"The empirical formula gives…",
          a:"The simplest whole-number ratio of atoms",
          x:["The actual number of atoms in a molecule","The mass of one mole","The ratio of ions only"],
          e:"Empirical = simplest ratio (e.g. CH₂O). Molecular = actual numbers (e.g. glucose C₆H₁₂O₆). Molecular = n × empirical." },
        { d:3, q:"A compound is 40.0% C, 6.7% H, 53.3% O by mass. Its empirical formula is…",
          a:"CH₂O", x:["C₂H₄O₂","CHO","CH₄O"],
          e:"Divide % by Ar: C 40/12=3.33, H 6.7/1=6.7, O 53.3/16=3.33. Ratio 1:2:1 → CH₂O.",
          acc:["ch2o"] },
        { d:2, q:"Molar concentration is calculated using…",
          a:"c = n / V (mol per dm³)", x:["c = m / V","c = n × V","c = V / n"],
          e:"Concentration c = amount of solute (mol) ÷ volume of solution (dm³). Units: mol dm⁻³ (shown as [X])." },
        { d:2, q:"How many moles of NaCl are in 250 cm³ of 0.20 mol dm⁻³ solution?",
          a:"0.050 mol", x:["0.20 mol","0.80 mol","50 mol"],
          e:"V = 250 cm³ = 0.250 dm³. n = c × V = 0.20 × 0.250 = 0.050 mol.",
          acc:["0.05","0.050"] },
        { d:3, q:"Avogadro's law states that equal volumes of gases (same T and P) contain…",
          a:"Equal numbers of molecules",
          x:["Equal masses","Equal numbers of atoms","The same density"],
          e:"At the same temperature and pressure, equal volumes of any gas contain equal numbers of molecules — so volume ratios equal mole ratios." }
      ]
    },
    {
      id: "s1_5", code: "1.5", theme: "Structure 1", region: "The Pressure Vaults",
      title: "Ideal Gases", sym: "He", hue: 205, hl: false, on: true,
      blurb: "Ideal gas assumptions, deviations, molar volume, PV = nRT.",
      q: [
        { d:2, q:"Which is a key assumption of the ideal gas model?",
          a:"Particles have negligible volume and no intermolecular forces",
          x:["Collisions lose kinetic energy","Particles attract strongly","Gas particles are stationary"],
          e:"Ideal gases: negligible particle volume, no intermolecular forces, and perfectly elastic collisions (no KE lost)." },
        { d:2, q:"Real gases deviate most from ideal behaviour at…",
          a:"Low temperature and high pressure",
          x:["High temperature and low pressure","Standard temperature and pressure","Absolute zero only"],
          e:"At low T and high P, particles are close and slow, so intermolecular forces and particle volume become significant." },
        { d:2, q:"In PV = nRT, what does n represent?",
          a:"Amount of gas in moles", x:["Number of molecules","Mass in grams","Number of atoms"],
          e:"n is the amount of substance in moles. P=pressure (Pa), V=volume (m³), R=gas constant, T=temperature (K)." },
        { d:1, q:"In the ideal gas equation, temperature must always be in…",
          a:"Kelvin", x:["Celsius","Fahrenheit","Joules"],
          e:"Temperature must be absolute (kelvin). Using °C gives wrong answers — always convert with K = °C + 273.",
          acc:["kelvin","k"] },
        { d:2, q:"At constant temperature, if the pressure on a fixed mass of gas doubles, its volume…",
          a:"Halves", x:["Doubles","Stays the same","Quadruples"],
          e:"At constant T, P and V are inversely proportional (Boyle's law): P₁V₁ = P₂V₂. Double P → half V." },
        { d:2, q:"At constant pressure, increasing the temperature of a gas causes its volume to…",
          a:"Increase", x:["Decrease","Stay constant","Drop to zero"],
          e:"At constant P, V is directly proportional to T (in kelvin): V₁/T₁ = V₂/T₂. Higher T → larger V." },
        { d:3, q:"A gas occupies 2.0 dm³ at 300 K. At constant pressure, its volume at 600 K is…",
          a:"4.0 dm³", x:["1.0 dm³","2.0 dm³","8.0 dm³"],
          e:"V₁/T₁ = V₂/T₂ → 2.0/300 = V₂/600 → V₂ = 4.0 dm³. Doubling kelvin temperature doubles the volume.",
          acc:["4","4.0"] },
        { d:3, q:"Why do real gases deviate from ideal behaviour?",
          a:"Particles have real volume and exert intermolecular forces",
          x:["Collisions are perfectly elastic","They obey PV = nRT exactly","Temperature has no effect"],
          e:"The ideal model ignores particle volume and intermolecular forces; real particles have both, causing deviation." }
      ]
    },

    /* ===================== STRUCTURE 2 ===================== */
    {
      id: "s2_1", code: "2.1", theme: "Structure 2", region: "The Lattice Citadel",
      title: "The Ionic Model", sym: "Na", hue: 25, hl: false, on: true,
      blurb: "Ions, ionic bonding, formulas & naming, lattices, properties.",
      q: [
        { d:1, q:"When a metal atom loses electrons it forms a…",
          a:"Cation (positive ion)", x:["Anion (negative ion)","Neutral atom","Molecule"],
          e:"Metals lose electrons → positive cations. Non-metals gain electrons → negative anions.",
          acc:["cation"] },
        { d:2, q:"An ionic bond is best described as…",
          a:"Electrostatic attraction between oppositely charged ions",
          x:["A shared pair of electrons","Delocalized electrons among cations","Weak dipole attraction"],
          e:"Ionic bonding = strong electrostatic attraction between cations and anions, forming a giant 3D lattice." },
        { d:2, q:"The formula of the ionic compound from Al³⁺ and O²⁻ is…",
          a:"Al₂O₃", x:["AlO","Al₃O₂","AlO₂"],
          e:"Balance charges: two Al³⁺ (+6) with three O²⁻ (−6) → Al₂O₃. Swap-and-drop the charges as subscripts.",
          acc:["al2o3"] },
        { d:2, q:"What is the formula of the carbonate ion?",
          a:"CO₃²⁻", x:["CO₂⁻","CO₃⁻","C₂O₃²⁻"],
          e:"Carbonate is CO₃²⁻. Other key polyatomic ions: nitrate NO₃⁻, sulfate SO₄²⁻, hydroxide OH⁻, ammonium NH₄⁺.",
          acc:["co3 2-","co3^2-"] },
        { d:1, q:"In naming binary ionic compounds, the anion takes the suffix…",
          a:"-ide", x:["-ate","-ite","-ium"],
          e:"Binary compounds: cation name + anion stem + 'ide' (e.g. sodium chloride). 'ate'/'ite' are for oxyanions." },
        { d:2, q:"Why do ionic compounds have high melting points?",
          a:"Strong electrostatic forces throughout the giant lattice need much energy to break",
          x:["Weak intermolecular forces","Delocalized electrons","Covalent network bonds"],
          e:"Many strong ionic attractions in the lattice require a large amount of energy to overcome → high mp/bp and low volatility." },
        { d:2, q:"Ionic compounds conduct electricity when…",
          a:"Molten or dissolved in water", x:["Solid","Always","Never"],
          e:"When molten or aqueous, ions are free to move and carry charge. In the solid, ions are fixed so it does NOT conduct." },
        { d:3, q:"Lattice enthalpy (strength of ionic bonding) increases with…",
          a:"Higher ionic charge and smaller ionic radius",
          x:["Lower charge and larger radius","Larger radius only","More neutrons"],
          e:"Greater charge and smaller ions sit closer with stronger attraction → larger lattice enthalpy (e.g. MgO ≫ NaCl)." }
      ]
    },
    {
      id: "s2_2", code: "2.2", theme: "Structure 2", region: "The Covalent Expanse",
      title: "The Covalent Model", sym: "O", hue: 215, hl: false, on: true,
      blurb: "Covalent bonds, Lewis, VSEPR shapes, polarity, IMFs, network solids.",
      q: [
        { d:1, q:"A covalent bond is formed by…",
          a:"A shared pair of electrons attracted to two nuclei",
          x:["Transfer of electrons","Delocalized electrons","Attraction between ions"],
          e:"Covalent bonding = electrostatic attraction between a shared pair of electrons and the positively charged nuclei." },
        { d:2, q:"As bond order increases from single → double → triple, the bond becomes…",
          a:"Shorter and stronger", x:["Longer and weaker","Longer and stronger","Shorter and weaker"],
          e:"More shared pairs pull nuclei closer: triple < double < single in length, and triple > double > single in strength." },
        { d:2, q:"According to VSEPR, a molecule with 4 bonding pairs and no lone pairs (e.g. CH₄) is…",
          a:"Tetrahedral, 109.5°", x:["Trigonal planar, 120°","Bent, 104.5°","Linear, 180°"],
          e:"Four electron domains repel to a tetrahedral shape with bond angles of 109.5° (e.g. methane).",
          acc:["tetrahedral"] },
        { d:3, q:"Water (2 bonding pairs, 2 lone pairs on O) has a shape and angle of…",
          a:"Bent, ~104.5°", x:["Linear, 180°","Tetrahedral, 109.5°","Trigonal pyramidal, 107°"],
          e:"4 domains → tetrahedral electron geometry, but 2 lone pairs push the H–O–H angle down to ~104.5°, giving a bent shape." },
        { d:2, q:"Which element is the most electronegative?",
          a:"Fluorine", x:["Oxygen","Chlorine","Nitrogen"],
          e:"Fluorine is the most electronegative element (4.0 on the Pauling scale). Electronegativity rises across a period and up a group.",
          acc:["fluorine","f"] },
        { d:3, q:"A molecule can have polar bonds but be NON-polar overall when…",
          a:"The bond dipoles are symmetrical and cancel",
          x:["It contains no lone pairs","The bonds are very strong","It has hydrogen bonds"],
          e:"e.g. CO₂ is linear so the two C=O dipoles cancel → non-polar molecule, despite polar bonds. Symmetry matters." },
        { d:2, q:"The strongest type of intermolecular force is…",
          a:"Hydrogen bonding", x:["London (dispersion) forces","Dipole–dipole forces","Ionic bonding"],
          e:"For comparable molar mass: London < dipole–dipole < hydrogen bonding. (Ionic/covalent are bonds, not intermolecular forces.)" },
        { d:3, q:"Hydrogen bonding occurs when H is covalently bonded to…",
          a:"N, O or F", x:["Any non-metal","C or H","A metal"],
          e:"Hydrogen bonds need H bonded to a small, highly electronegative atom — nitrogen, oxygen or fluorine — interacting with a lone pair on N/O/F nearby." },
        { d:3, q:"In diamond, each carbon atom is covalently bonded to…",
          a:"4 other carbons in a tetrahedral network",
          x:["3 others in layers","2 others in chains","1 other carbon"],
          e:"Diamond: each C bonded to 4 others → giant covalent network, very hard, high mp, non-conductor. Graphite: 3 bonds, layers, conducts." },
        { d:2, q:"Why does graphite conduct electricity but diamond does not?",
          a:"Graphite has delocalized electrons between its layers",
          x:["Graphite contains ions","Diamond has free electrons","Graphite is a metal"],
          e:"In graphite each C bonds to only 3 others, leaving one delocalized electron per atom free to move along the layers." }
      ]
    },
    {
      id: "s2_3", code: "2.3", theme: "Structure 2", region: "The Iron Bastion",
      title: "The Metallic Model", sym: "Fe", hue: 210, hl: false, on: true,
      blurb: "Metallic bonding, conductivity, malleability, bond strength.",
      q: [
        { d:1, q:"A metallic bond is the attraction between…",
          a:"A lattice of cations and a sea of delocalized electrons",
          x:["Oppositely charged ions","Shared pairs of electrons","Neutral atoms"],
          e:"Metallic bonding = electrostatic attraction between positive metal ions (cations) and delocalized (free) electrons." },
        { d:2, q:"Why are metals good electrical conductors?",
          a:"Delocalized electrons are free to move and carry charge",
          x:["Ions move through the lattice","Electrons are tightly bound","They contain mobile anions"],
          e:"The 'sea' of delocalized electrons moves freely, carrying charge (and heat) — so metals conduct in solid and molten states." },
        { d:2, q:"Why are metals malleable (can be hammered into shape)?",
          a:"Layers of cations can slide over each other while the electron sea holds them together",
          x:["The bonds are weak","They contain water","Electrons are fixed in place"],
          e:"When layers slide, the non-directional metallic bond is maintained by the delocalized electrons, so the metal deforms without shattering." },
        { d:3, q:"Metallic bond strength increases with…",
          a:"Greater ionic charge and smaller ionic radius",
          x:["Smaller charge and larger radius","More neutrons","Fewer delocalized electrons"],
          e:"More charge (more delocalized electrons) and smaller cations give a higher charge density and stronger bonding (higher mp), e.g. Na < Mg < Al." },
        { d:2, q:"Compared with sodium, magnesium has a higher melting point because Mg…",
          a:"Releases 2 delocalized electrons per atom and has a smaller, 2+ ion",
          x:["Has a larger atomic radius","Has fewer protons","Forms covalent bonds"],
          e:"Mg²⁺ has a higher charge and smaller radius than Na⁺ and contributes more delocalized electrons → stronger metallic bonding." },
        { d:3, q:"Transition elements often have high melting points because they have…",
          a:"Delocalized d-electrons adding to the metallic bonding",
          x:["Covalent networks","Weak metallic bonds","No delocalized electrons"],
          e:"Transition metals can delocalize both s and d electrons, giving stronger metallic bonding and high melting points." }
      ]
    },
    {
      id: "s2_4", code: "2.4", theme: "Structure 2", region: "The Materials Foundry",
      title: "From Models to Materials", sym: "Si", hue: 170, hl: false, on: true,
      blurb: "Bonding continuum / triangle, alloys, polymers.",
      q: [
        { d:2, q:"The bonding triangle represents bonding as…",
          a:"A continuum between ionic, covalent and metallic models",
          x:["Three completely separate categories","Only ionic and covalent","A measure of molar mass"],
          e:"Real bonding is a continuum; the triangle places a compound by the relative contribution of ionic, covalent and metallic character." },
        { d:3, q:"A compound's position in the bonding triangle is determined from…",
          a:"Electronegativity difference (ΔEN) and average electronegativity",
          x:["Molar mass and density","Melting point only","Number of atoms"],
          e:"Large ΔEN → ionic; small ΔEN with high average EN → covalent; low average EN → metallic." },
        { d:1, q:"An alloy is best described as…",
          a:"A mixture of a metal with other metals or non-metals",
          x:["A pure metal","An ionic compound","A covalent network"],
          e:"Alloys are mixtures (not compounds), e.g. bronze, brass, steel. Their components are not in a fixed ratio." },
        { d:2, q:"Alloys are often harder than pure metals because…",
          a:"Different-sized atoms disrupt the orderly layers, hindering sliding",
          x:["They contain covalent bonds","They have no delocalized electrons","They are ionic"],
          e:"Differently sized atoms distort the regular lattice so layers cannot slide easily — the alloy is harder and stronger. Bonding is non-directional." },
        { d:1, q:"Polymers are large molecules (macromolecules) built from repeating units called…",
          a:"Monomers", x:["Isotopes","Isomers","Ions"],
          e:"Monomers join to form polymers. Addition polymers form by opening C=C double bonds; condensation polymers release a small molecule (e.g. water).",
          acc:["monomers"] },
        { d:3, q:"Addition polymers form when…",
          a:"The C=C double bond in each monomer opens up to join the units",
          x:["A small molecule like water is released","Two functional groups react","Ions are exchanged"],
          e:"In addition polymerization (e.g. ethene → poly(ethene)), the double bond breaks and monomers link with 100% atom economy — no by-product." }
      ]
    },

    /* ===================== STRUCTURE 3 ===================== */
    {
      id: "s3_1", code: "3.1", theme: "Structure 3", region: "The Grand Periodic Hall",
      title: "The Periodic Table", sym: "Pt", hue: 320, hl: false, on: true,
      blurb: "Periods, groups, blocks, periodic trends, group 1 & 17, oxides.",
      q: [
        { d:1, q:"Elements in the same group of the periodic table have the same number of…",
          a:"Valence (outer) electrons", x:["Protons","Neutrons","Energy levels"],
          e:"Group number relates to valence electrons, which determines chemical behaviour. Period number = number of occupied energy levels." },
        { d:2, q:"Which blocks correspond to the sublevels being filled?",
          a:"s, p, d and f blocks", x:["Only s and p","Only metals and non-metals","Solid, liquid, gas"],
          e:"The table divides into s, p, d and f blocks based on the sublevel that the highest-energy electron occupies." },
        { d:2, q:"Across a period (left to right), atomic radius…",
          a:"Decreases", x:["Increases","Stays the same","Doubles"],
          e:"Across a period, nuclear charge increases while electrons add to the same level → stronger pull → smaller radius. Down a group it increases (more shells)." },
        { d:2, q:"Down a group, first ionization energy generally…",
          a:"Decreases", x:["Increases","Stays constant","Becomes zero"],
          e:"Down a group, outer electrons are farther from the nucleus and more shielded → easier to remove → lower IE. Across a period IE increases." },
        { d:2, q:"First ionization energy is the energy needed to…",
          a:"Remove one mole of electrons from one mole of gaseous atoms",
          x:["Add an electron to an atom","Break one mole of bonds","Melt one mole of metal"],
          e:"X(g) → X⁺(g) + e⁻. It measures how strongly the outer electron is held." },
        { d:2, q:"Reactivity of group 1 metals (alkali metals) down the group…",
          a:"Increases", x:["Decreases","Stays the same","Is zero"],
          e:"Down group 1, the outer electron is more easily lost (larger atom, more shielding), so reactivity with water increases (Li < Na < K)." },
        { d:3, q:"Reactivity of group 17 elements (halogens) down the group…",
          a:"Decreases", x:["Increases","Stays the same","Doubles"],
          e:"Halogens react by gaining an electron; larger atoms down the group attract electrons less strongly, so reactivity decreases (F₂ > Cl₂ > Br₂ > I₂)." },
        { d:3, q:"Across period 3, the oxides change from…",
          a:"Basic (metal) → amphoteric → acidic (non-metal)",
          x:["Acidic → basic","Neutral throughout","Basic throughout"],
          e:"Metal oxides (Na₂O, MgO) are basic; Al₂O₃ is amphoteric; non-metal oxides (SO₃, P₄O₁₀) are acidic." },
        { d:3, q:"What is the oxidation state of Mn in MnO₄⁻?",
          a:"+7", x:["+2","+4","−1"],
          e:"O is −2 (×4 = −8). Overall charge −1, so Mn + (−8) = −1 → Mn = +7." ,
          acc:["+7","7"] }
      ]
    },
    {
      id: "s3_2", code: "3.2", theme: "Structure 3", region: "The Carbon Labyrinth",
      title: "Organic: Functional Groups", sym: "Cₙ", hue: 95, hl: false, on: true,
      blurb: "Homologous series, naming, functional groups, isomers.",
      q: [
        { d:1, q:"Members of a homologous series differ by…",
          a:"A CH₂ unit", x:["A CH₃ unit","An H atom","A double bond"],
          e:"Each successive member differs by CH₂, has the same general formula and similar chemical properties with a gradual trend in physical properties." },
        { d:2, q:"The general formula of the alkanes is…",
          a:"CₙH₂ₙ₊₂", x:["CₙH₂ₙ","CₙH₂ₙ₋₂","CₙHₙ"],
          e:"Alkanes (saturated): CₙH₂ₙ₊₂. Alkenes (one C=C): CₙH₂ₙ. Alkynes (one C≡C): CₙH₂ₙ₋₂.",
          acc:["cnh2n+2"] },
        { d:2, q:"Which functional group defines an alcohol?",
          a:"Hydroxyl, –OH", x:["Carboxyl, –COOH","Carbonyl, C=O","Amino, –NH₂"],
          e:"Alcohols contain the hydroxyl group –OH (e.g. ethanol). Carboxylic acids have –COOH; aldehydes/ketones have C=O." },
        { d:2, q:"What is the name of CH₃CH₂CH₃?",
          a:"Propane", x:["Ethane","Butane","Propene"],
          e:"Three carbons, all single bonds → propane (prop = 3 C, -ane = alkane).",
          acc:["propane"] },
        { d:2, q:"The functional group of a carboxylic acid is…",
          a:"–COOH (carboxyl)", x:["–OH","–CHO","–NH₂"],
          e:"Carboxylic acids contain –COOH (e.g. ethanoic acid, CH₃COOH).",
          acc:["cooh","carboxyl"] },
        { d:3, q:"Structural isomers are compounds with…",
          a:"The same molecular formula but different structural arrangements",
          x:["Different molecular formulas","The same structure","Different numbers of atoms"],
          e:"Isomers share a molecular formula (e.g. C₄H₁₀) but differ in how atoms are connected (e.g. butane vs methylpropane)." },
        { d:1, q:"A compound containing a C=C double bond belongs to the…",
          a:"Alkenes", x:["Alkanes","Alcohols","Alkynes"],
          e:"Alkenes are unsaturated hydrocarbons with at least one C=C double bond (e.g. ethene, C₂H₄).",
          acc:["alkene","alkenes"] },
        { d:2, q:"Which formula type shows the simplest whole-number ratio of atoms?",
          a:"Empirical formula", x:["Molecular formula","Structural formula","Skeletal formula"],
          e:"Empirical = simplest ratio; molecular = actual numbers; structural/skeletal show how atoms are arranged/bonded." }
      ]
    },

    /* ===================== REACTIVITY 1 ===================== */
    {
      id: "r1_1", code: "1.1", theme: "Reactivity 1", region: "The Ember Crucible",
      title: "Measuring Enthalpy Changes", sym: "ΔH", hue: 12, hl: false, on: true,
      blurb: "Heat vs temperature, endo/exothermic, energy profiles, q = mcΔT.",
      q: [
        { d:1, q:"An exothermic reaction is one that…",
          a:"Releases energy to the surroundings (temperature rises)",
          x:["Absorbs energy (temperature falls)","Has no energy change","Only occurs when heated"],
          e:"Exothermic: energy released, surroundings warm up, ΔH is negative. Endothermic: energy absorbed, surroundings cool, ΔH positive." },
        { d:2, q:"For an endothermic reaction, the sign of ΔH is…",
          a:"Positive (+)", x:["Negative (−)","Zero","Always 1"],
          e:"Endothermic reactions absorb energy, so the products have more enthalpy than reactants → ΔH is positive." },
        { d:2, q:"What is the difference between heat and temperature?",
          a:"Heat is total energy transferred; temperature is average kinetic energy of particles",
          x:["They are the same thing","Heat is measured in kelvin","Temperature is energy in joules"],
          e:"Temperature (K) measures average particle KE; heat is the total thermal energy transferred between system and surroundings." },
        { d:2, q:"In an exothermic energy profile, the products are…",
          a:"Lower in potential energy than the reactants",
          x:["Higher in energy than reactants","Equal in energy to reactants","Always at zero energy"],
          e:"Exothermic: products lie below reactants (energy released). The axes are reaction coordinate (x) vs potential energy (y)." },
        { d:2, q:"The equation used to calculate heat energy is…",
          a:"q = mcΔT", x:["q = m/cΔT","q = mc/ΔT","q = c ΔT / m"],
          e:"q = mcΔT, where m = mass, c = specific heat capacity, ΔT = temperature change. ΔH = −q/n for the reaction.",
          acc:["q=mcdt","mcdeltat"] },
        { d:3, q:"100 g of water rises by 5.0 °C (c = 4.18 J g⁻¹ °C⁻¹). The heat absorbed is…",
          a:"2090 J", x:["418 J","20900 J","500 J"],
          e:"q = mcΔT = 100 × 4.18 × 5.0 = 2090 J (≈ 2.09 kJ).",
          acc:["2090","2.09 kj"] },
        { d:1, q:"The units of a standard enthalpy change, ΔH°, are…",
          a:"kJ mol⁻¹", x:["J g⁻¹","kJ","mol dm⁻³"],
          e:"ΔH° is quoted per mole of reaction, in kJ mol⁻¹, measured at constant pressure under standard conditions.",
          acc:["kj/mol","kj mol-1"] },
        { d:3, q:"Why do calorimetry experiments often give a smaller temperature change than expected?",
          a:"Heat is lost to the surroundings",
          x:["The reaction is endothermic","Water has a low heat capacity","Too much product forms"],
          e:"Heat loss to the surroundings (and incomplete reaction/combustion) means the measured ΔT — and so the calculated ΔH — is smaller in magnitude than the true value." }
      ]
    },
    {
      id: "r1_2", code: "1.2", theme: "Reactivity 1", region: "The Cycle Sanctum",
      title: "Energy Cycles & Bond Enthalpies", sym: "Hₛ", hue: 50, hl: false, on: true,
      blurb: "Bond breaking/making, Hess's law, enthalpy cycles.",
      q: [
        { d:1, q:"Breaking chemical bonds is…",
          a:"Endothermic (absorbs energy)", x:["Exothermic (releases energy)","Energy-neutral","Always spontaneous"],
          e:"Bond breaking absorbs energy; bond making releases energy. ΔH = Σ(bonds broken) − Σ(bonds formed)." },
        { d:2, q:"Using bond enthalpies, ΔH of a reaction equals…",
          a:"Σ(bonds broken) − Σ(bonds formed)",
          x:["Σ(bonds formed) − Σ(bonds broken)","Σ(bonds broken) + Σ(bonds formed)","bonds formed only"],
          e:"Energy in to break reactant bonds minus energy out from forming product bonds. Negative result → exothermic." },
        { d:2, q:"Hess's law states that the enthalpy change of a reaction…",
          a:"Is independent of the route taken between initial and final states",
          x:["Depends on the reaction pathway","Is always positive","Equals the activation energy"],
          e:"Because enthalpy is a state function, the total ΔH is the same whether direct or via intermediates — this lets us add cycles." },
        { d:3, q:"Why are bond enthalpy values described as 'average' values?",
          a:"The same bond has slightly different strengths in different molecules",
          x:["They are always exact","They ignore bond making","They are measured at 0 K"],
          e:"A C–H bond, for example, differs slightly between methane and ethanol, so tabulated values are averages — calculations are approximate." },
        { d:3, q:"Hess's law is a direct consequence of the law of…",
          a:"Conservation of energy", x:["Conservation of mass","Definite proportions","Avogadro"],
          e:"Energy cannot be created or destroyed, so the overall enthalpy change must be the same regardless of pathway." }
      ]
    },
    {
      id: "r1_3", code: "1.3", theme: "Reactivity 1", region: "The Combustion Wastes",
      title: "Energy from Fuels", sym: "🔥", hue: 20, hl: false, on: true,
      blurb: "Complete/incomplete combustion, fossil fuels, CO₂, biofuels.",
      q: [
        { d:2, q:"Complete combustion of a hydrocarbon produces…",
          a:"Carbon dioxide and water", x:["Carbon monoxide and water","Carbon and hydrogen","Only carbon dioxide"],
          e:"With plenty of oxygen: CₓHᵧ + O₂ → CO₂ + H₂O. Complete combustion maximizes energy released." },
        { d:2, q:"Incomplete combustion (limited oxygen) can produce…",
          a:"Carbon monoxide and carbon (soot)",
          x:["Only carbon dioxide and water","Only oxygen","Hydrogen gas"],
          e:"With insufficient O₂, products include toxic carbon monoxide (CO) and carbon (soot), and less energy is released." },
        { d:2, q:"Why is carbon monoxide dangerous?",
          a:"It is toxic — it binds to haemoglobin and reduces oxygen transport",
          x:["It is explosive at low levels","It is highly acidic","It is radioactive"],
          e:"CO is a colourless, odourless toxic gas that binds strongly to haemoglobin, preventing oxygen transport in the blood." },
        { d:1, q:"Which of these is a fossil fuel?",
          a:"Coal", x:["Bioethanol","Hydrogen","Solar power"],
          e:"Fossil fuels: coal, crude oil and natural gas. They are non-renewable and release CO₂ (a greenhouse gas) when burned." },
        { d:2, q:"Biofuels are considered renewable because…",
          a:"They are made from biomass that regrows over a short period",
          x:["They never release CO₂","They are made from crude oil","They contain no carbon"],
          e:"Biofuels come from recently living biomass (via photosynthesis), so the carbon is fixed and re-released over a short cycle — renewable, unlike fossil fuels." },
        { d:3, q:"Increasing atmospheric CO₂ contributes to…",
          a:"The enhanced greenhouse effect (global warming)",
          x:["The ozone hole","Acid rain from sulfur","Lower global temperatures"],
          e:"CO₂ absorbs infrared radiation, trapping heat. (Acid rain is mainly from SO₂/NOₓ; ozone depletion is a separate issue.)" }
      ]
    },

    /* ===================== REACTIVITY 2 ===================== */
    {
      id: "r2_1", code: "2.1", theme: "Reactivity 2", region: "The Stoichiometry Bazaar",
      title: "The Amount of Chemical Change", sym: "Σ", hue: 330, hl: false, on: true,
      blurb: "Equations, mole ratios, limiting reactant, yield, atom economy.",
      q: [
        { d:1, q:"In a balanced equation, the coefficients give the…",
          a:"Mole ratio of reactants and products",
          x:["Mass ratio in grams","Number of atoms only","Volume ratio of solids"],
          e:"Coefficients give the ratio in moles (and, for gases at the same T and P, the volume ratio)." },
        { d:2, q:"For N₂ + 3H₂ → 2NH₃, how many moles of NH₃ form from 6 mol H₂ (excess N₂)?",
          a:"4 mol", x:["2 mol","6 mol","3 mol"],
          e:"Ratio H₂ : NH₃ = 3 : 2. So 6 mol H₂ → (2/3)×6 = 4 mol NH₃.",
          acc:["4","4 mol"] },
        { d:2, q:"The limiting reactant is the one that…",
          a:"Is completely used up and determines the theoretical yield",
          x:["Is left over at the end","Is the heaviest","Is always the gas"],
          e:"The limiting reactant runs out first, so it controls how much product can form (the theoretical yield). The other is in excess." },
        { d:3, q:"Percentage yield is calculated as…",
          a:"(experimental yield ÷ theoretical yield) × 100",
          x:["(theoretical ÷ experimental) × 100","experimental − theoretical","mass of reactant ÷ product"],
          e:"% yield = (actual/experimental yield ÷ theoretical yield) × 100. It is below 100% due to side reactions, losses, or reversibility." },
        { d:2, q:"If the theoretical yield is 8.0 g and you obtain 6.0 g, the percentage yield is…",
          a:"75%", x:["133%","48%","2%"],
          e:"% yield = (6.0 / 8.0) × 100 = 75%.",
          acc:["75","75%"] },
        { d:3, q:"Atom economy measures…",
          a:"The proportion of reactant mass that ends up in the useful product",
          x:["How fast a reaction goes","The energy released","The purity of the product"],
          e:"Atom economy = (Mr of desired product ÷ total Mr of all products) × 100. High atom economy = less waste (green chemistry)." },
        { d:3, q:"An addition polymerization reaction has an atom economy of…",
          a:"100%", x:["50%","75%","0%"],
          e:"In addition polymerization, all atoms of the monomers end up in the polymer — no by-product — so atom economy is 100%.",
          acc:["100","100%"] }
      ]
    },
    {
      id: "r2_2", code: "2.2", theme: "Reactivity 2", region: "The Kinetic Storm",
      title: "How Fast? The Rate of Change", sym: "vₜ", hue: 75, hl: false, on: true,
      blurb: "Rate, collision theory, factors, activation energy, catalysts.",
      q: [
        { d:1, q:"Rate of reaction is defined as the change in…",
          a:"Concentration of reactant or product per unit time",
          x:["Mass of catalyst per second","Temperature per minute","Number of bonds"],
          e:"Rate = change in concentration (or amount/volume/mass) of a species per unit time." },
        { d:2, q:"According to collision theory, a reaction occurs only when particles collide with…",
          a:"Sufficient energy AND correct orientation",
          x:["Any energy at all","Low energy only","Maximum mass"],
          e:"Collisions must have energy ≥ activation energy and the correct geometry/orientation to be 'successful'." },
        { d:2, q:"Which change will increase the rate of a reaction?",
          a:"Increasing the temperature",
          x:["Decreasing concentration","Decreasing surface area","Removing the catalyst"],
          e:"Higher temperature → particles move faster and more collisions exceed the activation energy → faster rate. Concentration, surface area and catalysts also matter." },
        { d:2, q:"Activation energy (Eₐ) is…",
          a:"The minimum energy colliding particles need for a successful reaction",
          x:["The energy released by the reaction","The total energy of the products","The heat of combustion"],
          e:"Eₐ is the minimum energy needed for a collision to lead to reaction. A lower Eₐ means more collisions succeed." },
        { d:3, q:"A catalyst increases the rate of reaction by…",
          a:"Providing an alternative pathway with lower activation energy",
          x:["Increasing the activation energy","Raising the temperature","Being used up in the reaction"],
          e:"A catalyst offers a route with lower Eₐ, so a greater fraction of collisions succeed. It is not consumed overall." },
        { d:3, q:"On a Maxwell–Boltzmann distribution, raising the temperature…",
          a:"Shifts the curve right and increases the fraction of particles above Eₐ",
          x:["Lowers the activation energy","Decreases average kinetic energy","Has no effect on the curve"],
          e:"Higher T broadens and flattens the curve, shifting it to higher energies — more particles exceed Eₐ, so rate increases." },
        { d:2, q:"Increasing the surface area of a solid reactant increases rate because…",
          a:"More particles are exposed for collisions",
          x:["It raises the temperature","It lowers activation energy","It adds a catalyst"],
          e:"A larger surface area (e.g. a powder vs a lump) exposes more particles, so the collision frequency rises." }
      ]
    }
  ]
};
