/**
 * Skill routing for the UserPromptSubmit skill-router hook.
 *
 * Scores the user's prompt against skill frontmatter descriptions with plain
 * offline token matching and returns the best matches, marking each one as
 * installed in the active plugin or available on demand from the source
 * catalog. Slim profile plugins generated by scripts/plugin-profiles.js
 * record their source repository in ecc-profile.json at the plugin root, so
 * routing covers the FULL catalog even when only a slim profile is enabled.
 */

'use strict';

const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { parseFrontmatter } = require('./plugin-profiles');

const PROFILE_METADATA_FILE = 'ecc-profile.json';
const CACHE_TTL_MS = 6 * 60 * 60 * 1000;
const DEFAULT_MAX_RESULTS = 3;
const DEFAULT_MIN_SCORE = 3;

// Function words and generic task verbs only. Domain-ish words (test, fix,
// build, review, ...) stay routable because skills are named after them.
const STOPWORDS = new Set([
  'the', 'and', 'for', 'with', 'from', 'this', 'that', 'these', 'those',
  'have', 'has', 'had', 'you', 'your', 'our', 'are', 'was', 'were', 'been',
  'being', 'will', 'would', 'could', 'should', 'can', 'may', 'might', 'must',
  'not', 'but', 'into', 'onto', 'about', 'over', 'under', 'out', 'off',
  'when', 'where', 'what', 'which', 'who', 'whom', 'why', 'how', 'all',
  'any', 'some', 'each', 'more', 'most', 'other', 'such', 'only', 'also',
  'than', 'then', 'them', 'they', 'there', 'here', 'just', 'like', 'very',
  'really', 'please', 'help', 'want', 'need', 'make', 'made', 'using',
  'use', 'used', 'get', 'got', 'set', 'let', 'way', 'thing', 'things',
  'know', 'still', 'now', 'currently', 'something',
]);

/**
 * Lowercase, split on non-alphanumerics, drop stopwords and short tokens.
 * Long plurals also contribute their singular form so "hooks" matches "hook".
 */
function tokenize(text) {
  const tokens = new Set();
  for (const rawToken of String(text || '').toLowerCase().split(/[^a-z0-9]+/)) {
    if (rawToken.length < 3 || STOPWORDS.has(rawToken)) {
      continue;
    }
    tokens.add(rawToken);
    if (rawToken.length > 3 && rawToken.endsWith('s')) {
      tokens.add(rawToken.slice(0, -1));
    }
  }
  return tokens;
}

function listSkillDirs(skillsRoot) {
  if (!fs.existsSync(skillsRoot)) {
    return [];
  }
  return fs.readdirSync(skillsRoot, { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)
    .sort();
}

function readCatalog(sourceRoot) {
  const skillsRoot = path.join(sourceRoot, 'skills');
  const entries = [];
  for (const skillId of listSkillDirs(skillsRoot)) {
    const skillPath = path.join(skillsRoot, skillId, 'SKILL.md');
    if (!fs.existsSync(skillPath)) {
      continue;
    }
    const { description } = parseFrontmatter(fs.readFileSync(skillPath, 'utf8'));
    entries.push({ id: skillId, description });
  }
  return entries;
}

function catalogSignature(sourceRoot) {
  const skillsRoot = path.join(sourceRoot, 'skills');
  try {
    const stat = fs.statSync(skillsRoot);
    return { dirCount: listSkillDirs(skillsRoot).length, mtimeMs: stat.mtimeMs };
  } catch {
    return { dirCount: 0, mtimeMs: 0 };
  }
}

function cachePathFor(sourceRoot) {
  const digest = crypto.createHash('sha1').update(path.resolve(sourceRoot)).digest('hex').slice(0, 12);
  return path.join(os.tmpdir(), `ecc-skill-router-${digest}.json`);
}

/**
 * Catalog scan with a best-effort tmpdir cache. The signature only tracks
 * skill directory adds/removes, so edited descriptions can be stale for up
 * to the TTL — acceptable for routing hints, and it keeps the hook well
 * under the blocking-hook latency budget.
 */
function loadCatalog(sourceRoot) {
  const signature = catalogSignature(sourceRoot);
  const cachePath = cachePathFor(sourceRoot);

  try {
    const cached = JSON.parse(fs.readFileSync(cachePath, 'utf8'));
    if (cached.signature
      && cached.signature.dirCount === signature.dirCount
      && cached.signature.mtimeMs === signature.mtimeMs
      && Number.isFinite(cached.builtAt)
      && Date.now() - cached.builtAt < CACHE_TTL_MS
      && Array.isArray(cached.entries)) {
      return cached.entries;
    }
  } catch {
    // missing or unreadable cache: rebuild below
  }

  const entries = readCatalog(sourceRoot);
  try {
    fs.writeFileSync(cachePath, JSON.stringify({ signature, builtAt: Date.now(), entries }));
  } catch {
    // cache write is best-effort only
  }
  return entries;
}

/**
 * Resolve where the full skill catalog lives and which skills are installed
 * in the active plugin. Generated slim profiles carry an ecc-profile.json
 * pointing at their source repository; the full plugin routes over itself.
 */
function resolveRouterContext(pluginRoot) {
  const installedIds = new Set(listSkillDirs(path.join(pluginRoot, 'skills')));
  let sourceRoot = pluginRoot;

  const metadataPath = path.join(pluginRoot, PROFILE_METADATA_FILE);
  try {
    const metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));
    if (metadata && typeof metadata.sourceRoot === 'string'
      && fs.existsSync(path.join(metadata.sourceRoot, 'skills'))) {
      sourceRoot = metadata.sourceRoot;
    }
  } catch {
    // no profile metadata: plugin root is the catalog source
  }

  return { sourceRoot, installedIds };
}

/**
 * Score the prompt against the catalog. Skill-id token matches weigh 3,
 * description token matches weigh 1; ties break alphabetically so output
 * is deterministic.
 */
function routePrompt(prompt, options = {}) {
  const pluginRoot = options.pluginRoot;
  if (!pluginRoot) {
    throw new Error('routePrompt requires pluginRoot');
  }
  const maxResults = options.maxResults || DEFAULT_MAX_RESULTS;
  const minScore = options.minScore || DEFAULT_MIN_SCORE;

  const promptTokens = tokenize(prompt);
  if (promptTokens.size === 0) {
    return [];
  }

  const { sourceRoot, installedIds } = resolveRouterContext(pluginRoot);
  const scored = [];

  for (const entry of loadCatalog(sourceRoot)) {
    if (entry.id === 'ecc-catalog') {
      continue;
    }
    let score = 0;
    for (const token of tokenize(entry.id.replace(/-/g, ' '))) {
      if (promptTokens.has(token)) {
        score += 3;
      }
    }
    for (const token of tokenize(entry.description)) {
      if (promptTokens.has(token)) {
        score += 1;
      }
    }
    if (score >= minScore) {
      scored.push({
        id: entry.id,
        description: entry.description,
        score,
        installed: installedIds.has(entry.id),
        sourceRoot,
      });
    }
  }

  scored.sort((a, b) => b.score - a.score || a.id.localeCompare(b.id));
  return scored.slice(0, maxResults);
}

module.exports = {
  PROFILE_METADATA_FILE,
  tokenize,
  resolveRouterContext,
  routePrompt,
};
